word_1 = input("input the 1st word\n>")     #1
word_2 = input("input the 2nd word\n>")
word_3 = input("input the 3rd word\n>")
print(word_1 + word_2 + word_3)
def add_three():                            #2         
    x = input("input the 1st number\n>")
    x = int(x)
    y = input("input the 2nd number\n>")
    y = int(y)
    z = input("input the 3rd number\n>")
    z = int(z) 
    print(str(x) + " + " + str(y) + " + " + str(z) + " = " + str(x + y + z))
add_three()
def add_three():                           #3
    x = input("input the 1st number\n>")
    x = int(x)
    y = input("input the 2nd number\n>")
    y = int(y)
    z = input("input the 3rd number\n>")
    z = int(z) 
    print(str(x) + " + " + str(y) + " + " + str(z) + " = " + str(x + y + z))
add_three()