favorite_animal =input (" What is you favorite animal?\n>")
input_1 =input ("Why are they your favorite animal?\n>")
input_2 =input ("Whats you favorite thing about them?\n>")
input_3 =input ("Where are they from?\n>")
input_4 =input ("What do they eat?\n>")
print ("Your favorite animal is " + favorite_animal + "." + " they are you favorite because " + input_1 + "." + " They are from " + input_3 + " ," "and they eat " + input_4 + "." + " your favorite thing about them is " + input_2 + "." )